<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- Package versions for package references across all projects -->
  <PropertyGroup>
    <ImGuiVersion>3.1.0-experimental</ImGuiVersion>
    <SkiaSharpVersion>4.151.2</SkiaSharpVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <!-- Source Generators -->
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    
    <!-- Platform specific -->
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    <PackageVersion Include="Microsoft.Graphics.Win2D" Version="1.4.0" />
    
    <!-- Engine -->
    <PackageVersion Include="SkiaSharp" Version="$(SkiaSharpVersion)" />
    <PackageVersion Include="SkiaSharp.HarfBuzz" Version="$(SkiaSharpVersion)" />
    
    <!-- Graphics -->
    <PackageVersion Include="TerraFX.Interop.Windows" Version="10.0.26100.6" />
    <PackageVersion Include="TerraFX.Interop.D3D12MemoryAllocator" Version="3.1.0.1" />
    <PackageVersion Include="Vortice.Vulkan" Version="3.2.3" />
    
    <!-- Others -->
    <PackageVersion Include="DotRecast.Recast" Version="2026.3.1" />
    <PackageVersion Include="Hexa.NET.ImGui" Version="$(ImGuiVersion)" />
    
    <!-- Tools -->
    <PackageVersion Include="XenoAtom.CommandLine" Version="2.0.3" />
    
    <!-- Asset Pipeline -->
    <PackageVersion Include="Vortice.Dxc.Native" Version="1.0.5" />
    <PackageVersion Include="Silk.NET.Assimp" Version="2.23.0" />
    <PackageVersion Include="Vortice.SPIRV.Reflect" Version="1.0.6" />
    <PackageVersion Include="Alimer.Bindings.MeshOptimizer" Version="1.2.1" />
    <PackageVersion Include="FreeTypeSharp" Version="3.1.0" />
    <PackageVersion Include="BCnEncoder.Net" Version="2.3.0" />
    <PackageVersion Include="Hexa.NET.DirectXTex" Version="2.0.4" />
    <PackageVersion Include="Slangc.NET" Version="2026.16.1" />
    
    <!-- Tests -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="NUnit" Version="4.6.1" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.3.0" />
  </ItemGroup>
</Project>
