<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(_AlimerDotNetTfm);$(AlimerPlatforms)</TargetFrameworks>
    <RootNamespace>Alimer.Physics</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>.generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alimer.SourceGenerator\Alimer.SourceGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alimer\Alimer.csproj" />
  </ItemGroup>

  <!-- Native Libraries-->
  <ItemGroup>
    <None Include="$(AlimerNativeDirectory)win-x64\box3d.dll">
      <CopyToOutputDirectory Condition="('$(RuntimeIdentifier)' == '' and $([MSBuild]::IsOSPlatform('Windows'))) == 'true' or '$(RuntimeIdentifier)' == 'win-x64'">PreserveNewest</CopyToOutputDirectory>
      <PackagePath>runtimes\win-x64\native</PackagePath>
      <Pack>True</Pack>
      <Visible>False</Visible>
    </None>
    <None Include="$(AlimerNativeDirectory)win-arm64\box3d.dll">
      <CopyToOutputDirectory Condition="('$(RuntimeIdentifier)' == '' and $([MSBuild]::IsOSPlatform('Windows'))) == 'true' or '$(RuntimeIdentifier)' == 'win-arm64'">PreserveNewest</CopyToOutputDirectory>
      <PackagePath>runtimes\win-arm64\native</PackagePath>
      <Pack>True</Pack>
      <Visible>False</Visible>
    </None>
  </ItemGroup>


</Project>
