// Copyright © Amer Koleci and Contributors.
// Licensed under the MIT License (MIT). See LICENSE in the repository root for more information.

#include "Graphics/PixelFormat.h"

namespace Alimer
{
	const PixelFormatInfo kFormatDesc[] = {
        //        format                    name                bytes blk         kind               red   green   blue  alpha  depth  stencl signed  srgb
        { PixelFormat::Undefined,           "Undefined",        0,   0, PixelFormatKind::Integer,      false, false, false, false, false, false, false, false },
        { PixelFormat::R8Unorm,             "R8Unorm",          1,   1, PixelFormatKind::Normalized,   true,  false, false, false, false, false, false, false },
        { PixelFormat::R8Snorm,             "R8Snorm",          1,   1, PixelFormatKind::Normalized,   true,  false, false, false, false, false, false, false },
        { PixelFormat::R8Uint,              "R8Uint",           1,   1, PixelFormatKind::Integer,      true,  false, false, false, false, false, false, false },
        { PixelFormat::R8Sint,              "R8Sint",           1,   1, PixelFormatKind::Integer,      true,  false, false, false, false, false, true,  false },
        { PixelFormat::R16Unorm,            "R16Unorm",         2,   1, PixelFormatKind::Normalized,   true,  false, false, false, false, false, false, false },
        { PixelFormat::R16Snorm,            "R16Snorm",         2,   1, PixelFormatKind::Normalized,   true,  false, false, false, false, false, false, false },
        { PixelFormat::R16Uint,             "R16Uint",          2,   1, PixelFormatKind::Integer,      true,  false, false, false, false, false, false, false },
        { PixelFormat::R16Sint,             "R16Sint",          2,   1, PixelFormatKind::Integer,      true,  false, false, false, false, false, true,  false },
        { PixelFormat::R16Float,            "R16Float",         2,   1, PixelFormatKind::Float,        true,  false, false, false, false, false, true,  false },
        { PixelFormat::RG8Unorm,            "RG8Unorm",         2,   1, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::RG8Snorm,            "RG8Snorm",         2,   1, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::RG8Uint,             "RG8Uint",          2,   1, PixelFormatKind::Integer,      true,  true,  false, false, false, false, false, false },
        { PixelFormat::RG8Sint,             "RG8Sint",          2,   1, PixelFormatKind::Integer,      true,  true,  false, false, false, false, true,  false },
        { PixelFormat::BGRA4Unorm,          "BGRA4Unorm",       2,   1, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::B5G6R5Unorm,         "B5G6R5Unorm",      2,   1, PixelFormatKind::Normalized,   true,  true,  true,  false, false, false, false, false },
        { PixelFormat::B5G5R5A1Unorm,       "B5G5R5A1Unorm",    2,   1, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::R32Uint,             "R32Uunt",          4,   1, PixelFormatKind::Integer,      true,  false, false, false, false, false, false, false },
        { PixelFormat::R32Sint,             "R32Sunt",          4,   1, PixelFormatKind::Integer,      true,  false, false, false, false, false, true,  false },
        { PixelFormat::R32Float,            "R32Float",         4,   1, PixelFormatKind::Float,        true,  false, false, false, false, false, true,  false },
        { PixelFormat::RG16Unorm,           "RG16Unorm",        4,   1, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::RG16Snorm,           "RG16Snorm",        4,   1, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::RG16Uint,            "RG16Uunt",         4,   1, PixelFormatKind::Integer,      true,  true,  false, false, false, false, false, false },
        { PixelFormat::RG16Sint,            "RG16Sunt",         4,   1, PixelFormatKind::Integer,      true,  true,  false, false, false, false, true,  false },
        { PixelFormat::RG16Float,           "RG16Float",        4,   1, PixelFormatKind::Float,        true,  true,  false, false, false, false, true,  false },
        { PixelFormat::RGBA8Unorm,          "RGBA8Unorm",       4,   1, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::RGBA8UnormSrgb,      "RGBA8UnormSrgb",   4,   1, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, true  },
        { PixelFormat::RGBA8Snorm,          "RGBA8Snorm",       4,   1, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::RGBA8Uint,           "RGBA8Uint",        4,   1, PixelFormatKind::Integer,      true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::RGBA8Sint,           "RGBA8Sint",        4,   1, PixelFormatKind::Integer,      true,  true,  true,  true,  false, false, true,  false },
        { PixelFormat::BGRA8Unorm,          "BGRA8Unorm",       4,   1, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::BGRA8UnormSrgb,      "BGRA8UnormSrgb",   4,   1, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::RGB10A2Unorm,        "RGB10A2Unorm",     4,   1, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::RG11B10Float,        "RG11B10Float",     4,   1, PixelFormatKind::Float,        true,  true,  true,  false, false, false, false, false },
        { PixelFormat::RGB9E5Float,         "RGB9E5Float",      4,   1, PixelFormatKind::Float,        true,  true,  true,  false, false, false, false, false },
        { PixelFormat::RG32Uint,            "RG32Uint",         8,   1, PixelFormatKind::Integer,      true,  true,  false, false, false, false, false, false },
        { PixelFormat::RG32Sint,            "RG32Sint",         8,   1, PixelFormatKind::Integer,      true,  true,  false, false, false, false, true,  false },
        { PixelFormat::RG32Float,           "RG32Float",        8,   1, PixelFormatKind::Float,        true,  true,  false, false, false, false, true,  false },
        { PixelFormat::RGBA16Unorm,         "RGBA16Uiorm",      8,   1, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::RGBA16Snorm,         "RGBA16Siorm",      8,   1, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::RGBA16Uint,          "RGBA16Uint",       8,   1, PixelFormatKind::Integer,      true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::RGBA16Sint,          "RGBA16Sint",       8,   1, PixelFormatKind::Integer,      true,  true,  true,  true,  false, false, true,  false },
        { PixelFormat::RGBA16Float,         "RGBA16Float",      8,   1, PixelFormatKind::Float,        true,  true,  true,  true,  false, false, true,  false },
        //{ PixelFormat::RGB32_UINT,        "RGB32_UINT",        12,  1, PixelFormatKind::Integer,      true,  true,  true,  false, false, false, false, false },
        //{ PixelFormat::RGB32_SINT,        "RGB32_SINT",        12,  1, PixelFormatKind::Integer,      true,  true,  true,  false, false, false, true,  false },
        //{ PixelFormat::RGB32_FLOAT,       "RGB32_FLOAT",       12,  1, PixelFormatKind::Float,        true,  true,  true,  false, false, false, true,  false },
        { PixelFormat::RGBA32Uint,          "RGBA32Uint",       16,  1, PixelFormatKind::Integer,      true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::RGBA32Sint,          "RGBA32Sint",       16,  1, PixelFormatKind::Integer,      true,  true,  true,  true,  false, false, true,  false },
        { PixelFormat::RGBA32Float,         "RGBA32Float",      16,  1, PixelFormatKind::Float,        true,  true,  true,  true,  false, false, true,  false },
        { PixelFormat::Depth16Unorm,        "Depth16Unorm",     2,   1, PixelFormatKind::DepthStencil, false, false, false, false, true,  false, false, false },
        { PixelFormat::Depth32Float,        "Depth32Float",     4,   1, PixelFormatKind::DepthStencil, false, false, false, false, true,  false, false, false },
        { PixelFormat::Depth24UnormStencil8, "Depth24UnormStencil8",    4,   1, PixelFormatKind::DepthStencil, false, false, false, false, true,  true,  false, false },
        { PixelFormat::Depth32FloatStencil8, "Depth32FloatStencil8",    8,   1, PixelFormatKind::DepthStencil, false, false, false, false, true,  true,  false, false },
        //{ PixelFormat::X24G8_UINT,        "X24G8_UINT",        4,   1, PixelFormatKind::Integer,      false, false, false, false, false, true,  false, false },
        //{ PixelFormat::X32G8_UINT,        "X32G8_UINT",        8,   1, PixelFormatKind::Integer,      false, false, false, false, false, true,  false, false },
        { PixelFormat::BC1RGBAUnorm,        "BC1RGBAUnorm",         8,   4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::BC1RGBAUnormSrgb,    "BC1RGBAUnormSrgb",     8,   4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, true  },
        { PixelFormat::BC2RGBAUnorm,        "BC2RGBAUnorm",         16,  4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::BC2RGBAUnormSrgb,    "BC2RGBAUnormSrgb",     16,  4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, true  },
        { PixelFormat::BC3RGBAUnorm,        "BC3RGBAUnorm",         16,  4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::BC3RGBAUnormSrgb,    "BC3RGBAUnormSrgb",     16,  4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, true  },
        { PixelFormat::BC4RUnorm,           "BC4RUnorm",            8,   4, PixelFormatKind::Normalized,   true,  false, false, false, false, false, false, false },
        { PixelFormat::BC4RSnorm,           "BC4RSnorm",            8,   4, PixelFormatKind::Normalized,   true,  false, false, false, false, false, false, false },
        { PixelFormat::BC5RGUnorm,          "BC5RGUnorm",           16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::BC5RGSnorm,          "BC5RGSnorm",           16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::BC6HRGBFloat,        "BC6HRGBFloat",         16,  4, PixelFormatKind::Float,        true,  true,  true,  false, false, false, true,  false },
        { PixelFormat::BC6HRGBUFloat,       "BC6HRGBUFloat",        16,  4, PixelFormatKind::Float,        true,  true,  true,  false, false, false, false, false },
        { PixelFormat::BC7RGBAUnorm,        "BC7RGBAUnorm",         16,  4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::BC7RGBAUnormSrgb,    "BC7RGBAUnormSrgb",     16,  4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, true  },
        // EAC/ETC compressed formats
        { PixelFormat::ETC2RGB8Unorm,       "ETC2RGB8Unorm",         8,   4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::ETC2RGB8UnormSrgb,   "ETC2RGB8UnormSrgb",     8,   4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, true  },
        { PixelFormat::ETC2RGB8A1Unorm,     "ETC2RGB8A1Unorm",         16,  4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::ETC2RGB8A1UnormSrgb, "ETC2RGB8A1UnormSrgb",     16,  4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, true  },
        { PixelFormat::ETC2RGBA8Unorm,      "ETC2RGBA8Unorm",         16,  4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::ETC2RGBA8UnormSrgb,  "ETC2RGBA8UnormSrgb",     16,  4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, true  },
        { PixelFormat::EACR11Unorm,         "EACR11Unorm",            8,   4, PixelFormatKind::Normalized,   true,  false, false, false, false, false, false, false },
        { PixelFormat::EACR11Snorm,         "EACR11Snorm",            8,   4, PixelFormatKind::Normalized,   true,  false, false, false, false, false, false, false },
        { PixelFormat::EACRG11Unorm,        "EACRG11Unorm",           16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::EACRG11Snorm,        "EACRG11Snorm",           16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        // ASTC compressed formats
        { PixelFormat::ASTC4x4Unorm,        "ASTC4x4Unorm",             8,   4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::ASTC4x4UnormSrgb,    "ASTC4x4UnormSrgb",         8,   4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, true  },
        { PixelFormat::ASTC5x4Unorm,        "ASTC5x4Unorm",             16,  4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::ASTC5x4UnormSrgb,    "ASTC5x4UnormSrgb",         16,  4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, true  },
        { PixelFormat::ASTC5x5Unorm,        "ASTC5x5Unorm",             16,  4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, false },
        { PixelFormat::ASTC5x5UnormSrgb,    "ASTC5x5UnormSrgb",         16,  4, PixelFormatKind::Normalized,   true,  true,  true,  true,  false, false, false, true  },
        { PixelFormat::ASTC6x5Unorm,        "ASTC6x5Unorm",             8,   4, PixelFormatKind::Normalized,   true,  false, false, false, false, false, false, false },
        { PixelFormat::ASTC6x5UnormSrgb,    "ASTC6x5UnormSrgb",         8,   4, PixelFormatKind::Normalized,   true,  false, false, false, false, false, false, false },
        { PixelFormat::ASTC6x6Unorm,        "ASTC6x6Unorm",             16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC6x6UnormSrgb,    "ASTC6x6UnormSrgb",         16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC8x5Unorm,        "ASTC8x5Unorm",             16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC8x5UnormSrgb,    "ASTC8x5UnormSrgb",         16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC8x6Unorm,        "ASTC8x6Unorm",             16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC8x6UnormSrgb,    "ASTC8x6UnormSrgb",         16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC8x8Unorm,        "ASTC8x8Unorm",             16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC8x8UnormSrgb,    "ASTC8x8UnormSrgb",         16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC10x5Unorm,       "ASTC10x5Unorm",             16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC10x5UnormSrgb,   "ASTC10x5UnormSrgb",         16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC10x6Unorm,       "ASTC10x6Unorm",             16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC10x6UnormSrgb,   "ASTC10x6UnormSrgb",         16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC10x8Unorm,       "ASTC10x8Unorm",             16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC10x8UnormSrgb,   "ASTC10x8UnormSrgb",         16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC10x10Unorm,      "ASTC10x10Unorm",             16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC10x10UnormSrgb,  "ASTC10x10UnormSrgb",         16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC12x10Unorm,      "ASTC12x10Unorm",             16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC12x10UnormSrgb,  "ASTC12x10UnormSrgb",         16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC12x12Unorm,      "ASTC12x12Unorm",             16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
        { PixelFormat::ASTC12x12UnormSrgb,  "ASTC12x12UnormSrgb",         16,  4, PixelFormatKind::Normalized,   true,  true,  false, false, false, false, false, false },
	};

    const PixelFormatInfo& GetFormatInfo(PixelFormat format)
    {
        static_assert(sizeof(kFormatDesc) / sizeof(PixelFormatInfo) == size_t(PixelFormat::Count),
            "The format info table doesn't have the right number of elements");

        if (uint32_t(format) >= uint32_t(PixelFormat::Count))
            return kFormatDesc[0]; // UNKNOWN

        const PixelFormatInfo& info = kFormatDesc[uint32_t(format)];
        ALIMER_ASSERT(info.format == format);
        return info;
    }
}
