// Copyright (c) Amer Koleci and Contributors.
// Licensed under the MIT License (MIT). See LICENSE in the repository root for more information.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Alimer.SourceGenerators;

internal static class Extensions
{
    public static string FullName(this ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);


    public static bool IsEnum(this SyntaxNode node) => node is EnumDeclarationSyntax;

    public static bool IsStruct(this SyntaxNode node) => node is StructDeclarationSyntax;

    public static bool IsClass(this SyntaxNode node) => node is ClassDeclarationSyntax;

    public static bool IsRecordStruct(this SyntaxNode node)
        => node is RecordDeclarationSyntax recordDecl && recordDecl.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword);

    public static bool IsPartial(this SyntaxNode node)
        => node is TypeDeclarationSyntax type && type.Modifiers.Any(SyntaxKind.PartialKeyword);
    public static bool IsRef(this SyntaxNode node)
        => node is TypeDeclarationSyntax type && type.Modifiers.Any(SyntaxKind.RefKeyword);

    public static FormattedBuilder AppendAutoGenerated(this FormattedBuilder builder)
    {
        return builder
            .AppendLine("// <auto-generated/>")
            ;
    }

    public static FormattedBuilder AppendOpenBracer(this FormattedBuilder builder)
        => builder
            .AppendLine("{")
            .BeginIndentation();

    public static FormattedBuilder AppendCloseBracer(this FormattedBuilder builder, string extra = "")
        => builder
            .EndIndentation()
            .AppendLine("}" + $"{extra}");
}
