// Copyright (c) Amer Koleci and Contributors.
// Licensed under the MIT License (MIT). See LICENSE in the repository root for more information.

using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Alimer.SourceGenerators;

[Generator]
internal sealed class TypeMetadataGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        DebugGuard.MaybeLaunchDebuggerOnStartup();

        IncrementalValuesProvider<TypeMetadataGenerate> classDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
           fullyQualifiedMetadataName: AlimerTypes.MetaAttribute,
           predicate: IsTypeCandidate,
           transform: static (context, token) =>
           {
               INamedTypeSymbol classSymbol = (INamedTypeSymbol)context.TargetSymbol;

               return new TypeMetadataGenerate((BaseTypeDeclarationSyntax)context.TargetNode, classSymbol, context.SemanticModel, context.Attributes);
           });

        IncrementalValueProvider<(Compilation Left, ImmutableArray<TypeMetadataGenerate> Right)> valueProvider =
            context
            .CompilationProvider
            .Combine(classDeclarations.Collect());

        context
            .RegisterSourceOutput(valueProvider, static (productionContext, source) => Execute(source.Left, source.Right!, productionContext));

        static void Execute(Compilation _, ImmutableArray<TypeMetadataGenerate> types, SourceProductionContext context)
        {
            foreach (TypeMetadataGenerate asset in types)
            {
                string source = Build(asset);
                context.AddSource($"{asset.Symbol.Name}.g.cs", source);
            }
        }
    }

    public static bool IsTypeCandidate(SyntaxNode node, CancellationToken _)
    {
        if (!node.IsPartial())
            return false;

        return node.IsClass() || node.IsStruct() || node.IsEnum();
    }

    public static string Build(in TypeMetadataGenerate typeGenerate)
    {
        TypeDeclarationSyntax typeDecl = (TypeDeclarationSyntax)typeGenerate.Node;
        INamedTypeSymbol symbol = typeGenerate.Symbol;
        //var type = assetType.Type;
        FormattedBuilder builder = new(new StringBuilder());

        string? entityFactoryType = default;

        foreach (var attr in typeDecl.AttributeLists)
        {
            foreach (var arg in attr.Attributes)
            {
                if (arg.Name.ToString() == "DefaultEntitySystem")
                {
                    var argExpr = arg.ArgumentList.Arguments[0];
                    var argValue = argExpr.Expression.NormalizeWhitespace().ToString();

                    if(argValue.StartsWith("nameof("))
                    {
                        argValue = $"\"{Code.NameOf(argValue)}\"";
                    }
                    else if (argExpr.Expression is TypeOfExpressionSyntax typeOfExpression)
                    {
                        TypeInfo typeInfo = typeGenerate.SemanticModel.GetTypeInfo(typeOfExpression.Type);
                        ITypeSymbol? type = typeInfo.Type;

                        argValue = type.ToString();
                    }

                    argValue = argValue.StartsWith("nameof(") ? $"\"{Code.NameOf(argValue)}\"" : argValue;

                    entityFactoryType = argValue;
                }

                foreach (var attribute in typeGenerate.Attributes)
                {
                    if (attribute.AttributeClass!.Name.EndsWith("DefaultEntitySystem"))
                    {
                        // Process the MetaAttribute if needed
                        // For example, you can read constructor arguments or named arguments here
                        //entityFactoryType = attribute.ConstructorArguments[0].Type;
                        break;
                    }
                }
            }
        }

        builder
            .AppendAutoGenerated()
            .AppendLine()
            .AppendLine("using System.Text.Json.Nodes;")
            .AppendLine()
            .AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()};")
            .AppendLine()
            .AppendLine($"{symbol.DeclaredAccessibility.AsString()} partial class {symbol.Name}")
            .AppendOpenBracer()
                .AppendLine($"static {symbol.Name}()")
                .AppendOpenBracer();

        if (symbol.DerivesFrom("global::Alimer.Engine.Component"))
        {
            builder.AppendLine($"// COMPONENT");
        }

        foreach (var property in symbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (property.IsStatic || property.IsReadOnly)
                continue;

            if (FormattedBuilderExtensions.ShouldIgnore(property))
                continue;

            // Ignore non public properties
            if (property.DeclaredAccessibility != Accessibility.Public)
                continue;

            // Check if property is an enum

            builder.AppendLine($"//{property.Type} - {property.Name}");
        }

        foreach (var attr in typeDecl.AttributeLists)
        {
            foreach (var arg in attr.Attributes)
            {
                builder.AppendLine($"//{arg.Name}");
            }
        }

        if (entityFactoryType is not null)
        {
            builder.AppendLine($"global::Alimer.Engine.EntityManager.RegisterSystemFactory((services) => new {entityFactoryType}(services));");
        }
        else
        {
           
        }

        builder
        .AppendCloseBracer()
        //.Serialize(componentType)
        .AppendCloseBracer()
        ;

        return builder.ToString();
    }
}

internal readonly struct TypeMetadataGenerate(BaseTypeDeclarationSyntax node, INamedTypeSymbol symbol, SemanticModel semanticModel, ImmutableArray<AttributeData> attributes)
{
    public readonly BaseTypeDeclarationSyntax Node = node;
    public readonly INamedTypeSymbol Symbol = symbol;
    public readonly SemanticModel SemanticModel = semanticModel;
    public readonly ImmutableArray<AttributeData> Attributes = attributes;
}

public static class Code
{
    // Handwritten regex for nameof() expressions. Group 1 is what you want.
    public const string NAME_OF = @"(?:(?<=\.)?([^.<>\n]*)(?:<[^.\n]+>)?(?=$))";
    public static Regex NameOfRegex { get; set; } = new Regex(NAME_OF);

    /// <summary>
    /// Compute the nameof expression for a given string.
    /// </summary>
    /// <param name="input">Input text.</param>
    /// <returns>Equivalent value that nameof() would produce.</returns>
    public static string NameOf(string input)
    {
        var text = input.StartsWith("nameof(") ?
          input.Substring(7, input.Length - 8)
          : input;

        var match = NameOfRegex.Match(text);

        return match.Success ? match.Groups[1].Value : text;
    }
    /// <summary>
    /// Compute the nameof expression for a given string.
    /// </summary>
    /// <param name="input">Input text.</param>
    /// <returns>Equivalent value that nameof() would produce.</returns>
    public static string TypeOf(string input)
    {
        var text = input.StartsWith("typeof(") ?
          input.Substring(7, input.Length - 8)
          : input;

        var match = NameOfRegex.Match(text);

        return match.Success ? match.Groups[1].Value : text;
    }
}

internal static class FormattedBuilderExtensions
{
    public static FormattedBuilder Serialize(this FormattedBuilder builder, TypeMetadataGenerate typeGenerate)
    {
        INamedTypeSymbol symbol = typeGenerate.Symbol;
        if (symbol.IsAbstract)
            return builder;

        builder = builder
            .AppendLine()
            .AppendLine($"public override JsonObject Serialize()")
            .AppendOpenBracer()
                .AppendLine($"JsonObject json = new ()")
                .AppendOpenBracer()
                .AppendLine("{ \"__type\", " + $"\"{symbol.Name}\"" + " },")
                .AppendLine("{ \"__enabled\", " + $"IsEnabled" + " },")
                .AppendCloseBracer(";")
                .AppendLine()
                ;

        foreach (IPropertySymbol property in symbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (property.IsStatic || property.IsReadOnly)
                continue;

            if (ShouldIgnore(property))
                continue;

            string jsonName = $"\"{property.Name}\"";

            switch (property.Type.SpecialType)
            {
                case SpecialType.System_Boolean:
                case SpecialType.System_SByte:
                case SpecialType.System_Int16:
                case SpecialType.System_Int32:
                case SpecialType.System_Int64:
                case SpecialType.System_Byte:
                case SpecialType.System_UInt16:
                case SpecialType.System_UInt32:
                case SpecialType.System_UInt64:
                case SpecialType.System_Single:
                case SpecialType.System_Double:
                case SpecialType.System_Char:
                case SpecialType.System_String:
                    builder = builder.AppendLine($"json.Add({jsonName}, {property.Name});");
                    break;
                default:
                    builder = builder.AppendLine($"json.Add({jsonName}, JsonUtilities.ToNode({property.Name}));");
                    break;
            }
        }

        return builder
            .AppendLine("return json;")
            .AppendCloseBracer()
                ;
    }

    public static bool ShouldIgnore(this ISymbol symbol)
    {
        if (symbol == null)
            throw new ArgumentNullException(nameof(symbol));

        AttributeData? jsonAttribute = symbol.GetAttributes().FirstOrDefault(attr => attr.AttributeClass!.Name == "IgnoreDataMemberAttribute");
        if (jsonAttribute != null)
        {
            return true;
        }

        jsonAttribute = symbol.GetAttributes().FirstOrDefault(attr => attr.AttributeClass!.Name == "JsonIgnoreAttribute");
        if (jsonAttribute != null)
        {
            return true;
        }

        return false;
    }
}
