<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(_AlimerDotNetTfm)</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>Alimer.Shaders</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alimer.Shaders\Alimer.Shaders.csproj" />
  </ItemGroup>

</Project>
