name: Build Native Libs

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'src/native/**'
  pull_request:
    paths:
      - 'src/native/**'

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configure win-x64
      run: cmake -B build_win_64 -S src/native -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE:String=Release
    - name: Build win-x64
      run: cmake --build build_win_64 --config Release

    - name: Configure win-arm64
      run: cmake -B build_win_arm64 -S src/native . -G "Visual Studio 17 2022" -A ARM64 -DCMAKE_BUILD_TYPE:String=Release
    - name: Build win-arm64
      run: cmake --build build_win_arm64 --config Release

    - name: Package Windows
      run: |
        mkdir bin/win-x64/native
        mkdir bin/win-arm64/native
        mv build_win_64/bin/Release/SDL3.dll bin/win-x64/native
        mv build_win_arm64/bin/Release/SDL3.dll bin/win-arm64/native
    - uses: actions/upload-artifact@v3
      with:
        name: libs_windows
        path: bin

  update_libs:
    name: Update Native Libs
    runs-on: windows-latest
    needs: [windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Download windows lib
        uses: actions/download-artifact@v3
        with:
          name: libs_windows
          path: native
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: native
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: Updated native libs
          committer_name: GitHub Actions
          committer_email: actions@github.com