name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
    paths-ignore:
    - 'README.md'       

env:
  # common settings
  DOTNET_VERSION: 5.0.x

jobs:
  CheckSkipCI:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.pull_request.title, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[skip-ci]') &&
      !contains(github.event.pull_request.title, '[skip-ci]')
    steps:
      - run: exit 0

  Windows:
    runs-on: "windows-latest"
    needs: [CheckSkipCI]

    strategy:
      matrix:
        build_type: [Release]
    steps:
      - name: Checkout
        uses: actions/checkout@v2  

      - name: Configure and Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          mkdir build
          cd build
          cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX="SDK" -DCMAKE_BUILD_TYPE:STRING="Release" ..
          cmake --build . --target install --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 'Windows SDK ${{ matrix.build-type }}'
          path: build/SDK          