name: Build Native

on:
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/build_native.yml
      - 'src/native/**'
  pull_request:
    paths:
      - .github/workflows/build_native.yml
      - 'src/native/**'
  workflow_call:
  workflow_dispatch:

jobs:
  windows:
    name: Windows
    runs-on: windows-2025-vs2026
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Get CMake and Ninja
      uses: lukka/get-cmake@latest

    - name: Configure win-x64
      run: cmake -S "src/native" -B "build_win-x64" -G "Visual Studio 18 2026" -A x64 -DCMAKE_BUILD_TYPE=Distribution -DCMAKE_INSTALL_PREFIX="win-x64-sdk"
    - name: Build win-x64
      run: cmake --build build_win-x64 --target install --config Distribution --verbose --parallel

    - name: Configure win-arm64
      run: cmake -S "src/native" -B "build_win-arm64" -G "Visual Studio 18 2026" -A ARM64 -DCMAKE_BUILD_TYPE:String=Distribution -DCMAKE_INSTALL_PREFIX="win-arm64-sdk"
    - name: Build win-arm64
      run: cmake --build build_win-arm64 --target install --config Distribution

    - name: Package Windows
      run: |
        mkdir bin/win-x64
        mkdir bin/win-arm64
        mv win-x64-sdk\bin\*.dll bin/win-x64
        mv win-arm64-sdk\bin\*.dll bin/win-arm64

    - uses: actions/upload-artifact@v7
      with:
        name: libs_windows
        path: bin

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Get CMake and Ninja
      uses: lukka/get-cmake@latest

    - name: CMake Configure osx-universal
      run: cmake -S "src/native" -B "build_osx" -G Ninja -DCMAKE_BUILD_TYPE:String=Distribution -DCMAKE_INSTALL_PREFIX="osx-universal-sdk" -D"CMAKE_OSX_ARCHITECTURES=x86_64;arm64"
    - name: CMake Build osx-universal
      run: cmake --build build_osx --config Distribution --target install

    - name: Package macos
      run: |
        mkdir -p bin/osx
        mv osx-universal-sdk/lib/*.* bin/osx

    - uses: actions/upload-artifact@v7
      with:
        name: libs_osx
        path: bin

  combine:
    name: Combine artifacts
    runs-on: ubuntu-latest
    needs:  [windows, macos]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifacts

      - name: Combine
        run: |
          mkdir native_libs
          cp -r artifacts/libs_windows/* native_libs
          cp -r artifacts/libs_osx/* native_libs

      - uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z native_libs.7z ./native_libs/

      - uses: actions/upload-artifact@v7
        with:
          name: 'Build Artifacts'
          path: native_libs.7z
      - uses: geekyeggo/delete-artifact@v6
        with:
          name: |
            libs_windows
            libs_osx
