name: Build Native

on:
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/build_native.yml
      - 'src/native/**'
  pull_request:
    paths:
      - .github/workflows/build_native.yml
      - 'src/native/**'
  workflow_call:
  workflow_dispatch:
  
jobs:
  build:
    name: Native (${{ matrix.rid }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: win-x64
            runner: windows-2025-vs2026
            generator: "Visual Studio 18 2026"
            extraArgs: "-A x64"
          - rid: win-arm64
            runner: windows-2025-vs2026
            generator: "Visual Studio 18 2026"
            extraArgs: "-A ARM64"
          - rid: linux-x64
            runner: ubuntu-latest
            generator: "Ninja"
            extraArgs: ""
          - rid: osx-universal
            runner: macos-latest
            generator: "Ninja"
            extraArgs: "-DCMAKE_OSX_ARCHITECTURES=\"x86_64;arm64\""

    runs-on: ${{ matrix.runner }}
    steps:
    - name: Checkout
      uses: actions/checkout@v7
  
    - name: Get CMake and Ninja
      uses: lukka/get-cmake@latest
  
    - name: Install Linux dependencies
      if: startsWith(matrix.rid, 'linux-')
      run: |
        sudo apt-get update
        sudo apt-get install build-essential git make \
            pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
            libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
            libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
            libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
            libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Configure ${{ matrix.runner }}
      run: cmake -S "src/native" -B "build_${{ matrix.rid }}" -G "${{ matrix.generator }}" ${{ matrix.extraArgs }} -DCMAKE_BUILD_TYPE=Distribution -DCMAKE_INSTALL_PREFIX="${{ matrix.rid }}-sdk" -DALIMER_SAMPLES=OFF

    - name: Build ${{ matrix.rid }}
      run: cmake --build build_${{ matrix.rid }} --target install --config Distribution --verbose --parallel

    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.rid }}-sdk
        path: ${{ matrix.rid }}-sdk
