name: ci

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'CHANGELOG.md'
    - 'README.md'    
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
        - os: windows-latest
          runtime: win-x64
        - os: macos-latest
          runtime: osx-x64
        - os: ubuntu-latest
          runtime: linux-x64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Publish
      run: dotnet publish src --configuration Release --runtime ${{ matrix.runtime }} --output build/artifacts/${{ matrix.runtime }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.runtime }}
        path: build/artifacts/${{ matrix.runtime }}

    - name: Publish to NuGet
      if: github.event_name == 'push'
      run: |      
          if ( "${{github.ref}}" -match "^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$" ) {
              dotnet nuget push bin/packages/**/*.nupkg -s nuget.org -k ${{secrets.NUGET_TOKEN}}
          } else {
              echo "publish is only enabled by tagging with a release tag"
          }
