name: ci

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'CHANGELOG.md'
    - 'README.md'    
  pull_request:
    branches: [ main ]

jobs:
  CheckSkipCI:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.pull_request.title, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[skip-ci]') &&
      !contains(github.event.pull_request.title, '[skip-ci]')
    steps:
      - run: exit 0

  build:
    runs-on: windows-latest
    needs: [CheckSkipCI]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Version
      uses: aarnott/nbgv@v0.4.0
      with:
        setAllVars: true        

    - name: Pack
      run: dotnet pack src --configuration Release --output build/packages

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Packages
        path: build/packages